-- Tabla para almacenar la configuración de permisos por rol y empresa
CREATE TABLE IF NOT EXISTS roles_permisos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    rol VARCHAR(50) NOT NULL,
    id_empresa INT UNSIGNED NULL,
    auth_login TINYINT(1) NOT NULL DEFAULT 0,
    auth_logout TINYINT(1) NOT NULL DEFAULT 0,
    auth_password_reset TINYINT(1) NOT NULL DEFAULT 0,
    users_read TINYINT(1) NOT NULL DEFAULT 0,
    users_create TINYINT(1) NOT NULL DEFAULT 0,
    users_update TINYINT(1) NOT NULL DEFAULT 0,
    users_disable_enable TINYINT(1) NOT NULL DEFAULT 0,
    users_delete TINYINT(1) NOT NULL DEFAULT 0,
    roles_assign TINYINT(1) NOT NULL DEFAULT 0,
    roles_permissions_configure TINYINT(1) NOT NULL DEFAULT 0,
    inventory_products_read TINYINT(1) NOT NULL DEFAULT 0,
    inventory_products_create TINYINT(1) NOT NULL DEFAULT 0,
    inventory_products_update TINYINT(1) NOT NULL DEFAULT 0,
    inventory_products_delete TINYINT(1) NOT NULL DEFAULT 0,
    inventory_categories_read TINYINT(1) NOT NULL DEFAULT 0,
    inventory_categories_create TINYINT(1) NOT NULL DEFAULT 0,
    inventory_categories_update TINYINT(1) NOT NULL DEFAULT 0,
    inventory_categories_delete TINYINT(1) NOT NULL DEFAULT 0,
    inventory_subcategories_read TINYINT(1) NOT NULL DEFAULT 0,
    inventory_subcategories_create TINYINT(1) NOT NULL DEFAULT 0,
    inventory_subcategories_update TINYINT(1) NOT NULL DEFAULT 0,
    inventory_subcategories_delete TINYINT(1) NOT NULL DEFAULT 0,
    inventory_movements_quick_io TINYINT(1) NOT NULL DEFAULT 0,
    inventory_alerts_receive TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_areas_read TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_areas_create TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_areas_update TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_areas_delete TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_zones_read TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_zones_create TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_zones_update TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_zones_delete TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_assign_products_to_zone TINYINT(1) NOT NULL DEFAULT 0,
    warehouse_alerts_receive TINYINT(1) NOT NULL DEFAULT 0,
    reports_generate TINYINT(1) NOT NULL DEFAULT 0,
    reports_export_pdf TINYINT(1) NOT NULL DEFAULT 0,
    reports_export_xlsx TINYINT(1) NOT NULL DEFAULT 0,
    reports_schedule TINYINT(1) NOT NULL DEFAULT 0,
    reports_notify TINYINT(1) NOT NULL DEFAULT 0,
    log_read TINYINT(1) NOT NULL DEFAULT 0,
    log_export TINYINT(1) NOT NULL DEFAULT 0,
    log_analytics_view TINYINT(1) NOT NULL DEFAULT 0,
    log_flag_records TINYINT(1) NOT NULL DEFAULT 0,
    dashboard_view_metrics TINYINT(1) NOT NULL DEFAULT 0,
    notifications_receive_critical TINYINT(1) NOT NULL DEFAULT 0,
    account_profile_read TINYINT(1) NOT NULL DEFAULT 0,
    account_profile_update TINYINT(1) NOT NULL DEFAULT 0,
    account_theme_configure TINYINT(1) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_roles_permisos UNIQUE KEY (rol, id_empresa),
    CONSTRAINT fk_roles_permisos_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id_empresa) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Configuraciones predeterminadas por rol (aplican a todas las empresas cuando id_empresa es NULL)
INSERT INTO roles_permisos (
    rol,
    id_empresa,
    auth_login,
    auth_logout,
    auth_password_reset,
    users_read,
    users_create,
    users_update,
    users_disable_enable,
    users_delete,
    roles_assign,
    roles_permissions_configure,
    inventory_products_read,
    inventory_products_create,
    inventory_products_update,
    inventory_products_delete,
    inventory_categories_read,
    inventory_categories_create,
    inventory_categories_update,
    inventory_categories_delete,
    inventory_subcategories_read,
    inventory_subcategories_create,
    inventory_subcategories_update,
    inventory_subcategories_delete,
    inventory_movements_quick_io,
    inventory_alerts_receive,
    warehouse_areas_read,
    warehouse_areas_create,
    warehouse_areas_update,
    warehouse_areas_delete,
    warehouse_zones_read,
    warehouse_zones_create,
    warehouse_zones_update,
    warehouse_zones_delete,
    warehouse_assign_products_to_zone,
    warehouse_alerts_receive,
    reports_generate,
    reports_export_pdf,
    reports_export_xlsx,
    reports_schedule,
    reports_notify,
    log_read,
    log_export,
    log_analytics_view,
    log_flag_records,
    dashboard_view_metrics,
    notifications_receive_critical,
    account_profile_read,
    account_profile_update,
    account_theme_configure
) VALUES
    ('Administrador', NULL, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
    ('Supervisor', NULL, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
    ('Almacenista', NULL, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0),
    ('Mantenimiento', NULL, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
    ('Etiquetador', NULL, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1);
